# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Creater_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1034, 754)
        self.view = QtWidgets.QWidget(Dialog)
        self.view.setGeometry(QtCore.QRect(0, 0, 1041, 751))
        self.view.setStyleSheet("QWidget#view{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.00568182, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(54, 54, 54, 255))}")
        self.view.setObjectName("view")
        self.tabWidget = QtWidgets.QTabWidget(self.view)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1041, 761))
        self.tabWidget.setStyleSheet("settext:\'ПРив\'")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.view_2 = QtWidgets.QWidget(self.tab)
        self.view_2.setGeometry(QtCore.QRect(0, 0, 1041, 751))
        self.view_2.setStyleSheet("QWidget#view_2{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.00568182, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(54, 54, 54, 255))}")
        self.view_2.setObjectName("view_2")
        self.pushButton = QtWidgets.QPushButton(self.view_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 211, 51))
        self.pushButton.setStyleSheet("border-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0.242, y1:0.244318, x2:1, y2:0.978, stop:0 rgba(26, 88, 21, 255), stop:1 rgba(136, 255, 38, 255));\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.view_2)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 20, 231, 51))
        self.pushButton_2.setStyleSheet("border-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0.242, y1:0.244318, x2:1, y2:0.978, stop:0 rgba(26, 88, 21, 255), stop:1 rgba(136, 255, 38, 255));\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.view_2)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 991, 641))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.view_2)
        self.pushButton_4.setGeometry(QtCore.QRect(800, 20, 211, 51))
        self.pushButton_4.setStyleSheet("border-radius: 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0.242, y1:0.244318, x2:1, y2:0.978, stop:0 rgba(26, 88, 21, 255), stop:1 rgba(136, 255, 38, 255));\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 520, 551, 191))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Return page"))
        self.pushButton_2.setText(_translate("Dialog", "Use the photo"))
        self.pushButton_4.setText(_translate("Dialog", "START"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        self.pushButton_3.setText(_translate("Dialog", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))
